name: First Interaction Response

on:
  issues:
    types: [opened]

jobs:
  comment-on-issue:
  runs-on: ubuntu-latest
  steps:
    - name: Get Latest Issue Number
      id: get_issue
      run: echo "::set-output name=issue_number::$(curl -s -H \"Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}\" https://api.github.com/repos/${{ github.repository }}/issues | jq '.[0].number')"

    - name: Create Comment
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ steps.get_issue.outputs.issue_number }}
        body: |
          This is a multi-line test comment
          - With GitHub **Markdown** :sparkles:
          - Created by [create-or-update-comment][1]

          [1]: https://github.com/peter-evans/create-or-update-comment
        reactions: '+1'
